[package]
name = "indexlist"
version = "0.1.0"
authors = ["steveklabnik <steve@steveklabnik.com>"]

[dependencies]

[build-dependencies]
cc = "1.0"

[dev-dependencies]
generational-arena = "0.1"
criterion = "0.2"
rand = "0.5.5"

[[bench]]
name = "benchmarks"
harness = false
